### PR TITLE
CP-57 & CP-58: Add smoke tests for kafka-connect-jdbc and kafka-connect-hdfs.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@miguno @gwenshap These still need validation in the full packaging, especially since we resolved a few issues today that kept them from working properly. However, the gist of the test is there and I tested it with the tgz package from last night as best I could. Would be good to just try this out with the next round of packaging.

**Comment by miguno** [comment]
FYI: The new test already exposed at least one bug (CLASSPATH woes).  Will follow up tomorrow morning.

Gist of the required patch for the first bug I found, maybe there are more:

```diff
$ diff -u /usr/bin/connect-standalone.DIST /usr/bin/connect-standalone
--- /usr/bin/connect-standalone.DIST	2015-12-02 22:48:44.028832611 +0100
+++ /usr/bin/connect-standalone	2015-12-02 22:47:59.664661989 +0100
@@ -26,6 +26,11 @@
 # which are currently bundled with the Confluent schema-registry package
 CLASSPATH=$CLASSPATH:$base_dir/../share/java/kafka-serde-tools/*

+# Production jars
+for library in "confluent-common"; do
+  CLASSPATH=$CLASSPATH:$base_dir/../share/java/$library/*
+done
+
 if [ "x$KAFKA_LOG4J_OPTS" = "x" ]; then
   LOG4J_CONFIG_NORMAL_INSTALL="/etc/kafka/connect-log4j.properties"
   LOG4J_CONFIG_ZIP_INSTALL="$base_dir/../etc/kafka/connect-log4j.properties"
@@ -39,4 +44,5 @@
 fi
 export KAFKA_LOG4J_OPTS

+export CLASSPATH
 exec $(dirname $0)/kafka-run-class org.apache.kafka.connect.cli.ConnectStandalone "$@"
```

**Comment by ewencp** [comment]
@miguno See CP-87, I reported that issue (with effectively the same patch) there as well.

**Comment by ewencp** [comment]
@miguno I put the necessary patches into kafka-packaging (all 3 branches) and updated this patch to get the tests passing, at least in my test runs. Do you want to do a round of validation with the next iteration of packaging or shall we merge this based on my tests passing?

**Comment by miguno** [comment]
@ewencp:  Thanks for the patches, appreciated! (I actually did them on my side as well and noticed yours when I got a merge conflict, hehe.)  They are already merged.  If there are any issues we can fix them later, which I can take care of.

**Pull request merged**
